### ISSUE TITLE
Improve CSS of Scoreboard Page

### ISSUE THREAD

**Issue by imhardikdesai** [imhardikdesai/Quiz-App#2]
### Description

Improve CSS of Scoreboard Page

### Scope

- Improve CSS of Scoreboard Page, modified in mobile screen
![image](https://github.com/imhardikdesai/Quiz-App/assets/87645745/07d6a210-6bed-4e5d-b781-6c2cfeb3460f)

### Acceptance Criteria

- You can also Create an Separate issue for any Changes
- All scope are fix correctly, if you have made proper PR and changes then your PR merge by `hacktoberfest` and `hacktoberfest-accepted` label

### Labels

- CSS improvements
- Hacktoberfest

**Comment by suvraghosh** [comment]
Hey @imhardikdesai  interested to work on this issue if possible can you assign it to me ?

**Comment by mukulpythondev** [comment]
I want to contribute and give best results if you assign to me

**Comment by Tulsi5990** [comment]
Hey, i want to work on this. Can u please assign me?

**Comment by rishi457** [comment]
Hey, i want to work on this. Can u please assign me?

**Comment by Piyush07p** [comment]
can you assign it to me
